const dat = new Date(2016, 10, 21, 11, 2, 12);
console.log(dat);
console.log(dat.getFullYear());
console.log(dat.getMonth());
console.log(dat.getDate());
console.log(dat.getDay());
console.log(dat.getHours());
console.log(dat.getMinutes());
console.log(dat.getSeconds());
console.log(dat.getMilliseconds());
console.log(dat.getTime());
console.log(dat.getTimezoneOffset());

const dat2 = new Date();
dat2.setFullYear(2017);
dat2.setMonth(11);
dat2.setDate(12);
dat2.setHours(9);
dat2.setMinutes(12);
dat2.setSeconds(59);
console.log(dat2);
console.log(dat2.toLocaleString());
console.log(dat2.toDateString());
console.log(dat2.toTimeString());
console.log(dat2.toJSON());
